spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sdms
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: SDMS
