spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    # Effacer et recalculer les checksums (d√©veloppement uniquement)
    clear-checksums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sdms
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: SDMS

